version: '3.7'

# The configuration of all the services
services:
  # The configuration of the backend
  backend:
    # The folder where to build the backend's Dockerfile
    build: backend/simple-api-student
    # The network to use
    networks:
      - my-network
    # To run the database before the backend
    depends_on:
      - database

  database:
    # The folder where to build the database's Dockerfile
    build: database
    # The network to use
    networks:
      - my-network
    volumes:
      - /my/own/datadir:/var/lib/postgresql/data

  httpd:
    # The folder where to build the http server's Dockerfile
    build: httpserver
    # The port of connexion to the website
    ports:
      - "8080:80"
    # The network to use
    networks:
      - my-network
    # To run the database before the backend
    depends_on:
      - backend

# The configuration of the networks
networks:
  # My custom network
  my-network: