---
# tasks file for roles/httpserver

# Task to run the proxy
- name: Run proxy
  docker_container:
    # The name of the container
    name: httpserver
    # The image in my docker hub
    image: juuuju/takima_http_server
    # My network
    network_mode: app-network
    # The port
    ports:
      - 80:80