# Task to run the proxy
- name: Run HTTPD
  docker_container:
    # The name of the container
    name: httpserver
    # The image in my docker hub
    image: juuuju/takima_http_server:latest
    # My network
    network_mode: my_network
    # The port
    ports:
      - 80:80